### ISSUE TITLE
can mikado serialise use multi-CPU?

### ISSUE THREAD

**Issue by shenweima** [EI-CoreBioinformatics/mikado#177] opened 2019-05-26 03:06 UTC
I have a orf bed file containing 141655528 lines. I found it is very slow and mikado serialise only use single CPU when import data to sqlite3 db. ca this step use multi-CPU?
This is my command
`mikado serialise -p 12 --start-method spawn --json-conf configuration.yaml --xo_prepared_blastx.xml.gz --orfs mikado_prepared_orfs.bed --blast_targets /data2/user_data/blastx/plant_protein.fa --max_target_seqs 6`

**Comment by lucventurini** [comment] 2019-05-26 14:35
Dear @shenweima,
                                   Unfortunately no. I have only ever imported BED files that are much smaller than that, so that that section never posed too much of a problem. Internally, mikado will check each BED entry against the corresponding transcript (hence trying to check whether the orf is complete, whether it would be advisable to shrink it to find a Met codon). That, and the lack of multiprocessing, cause the slowness. 

I will have a look at how difficult it would be to implement this and will get back through this issue.

**Comment by shenweima** [comment] 2019-05-26 15:49
Thanks.  Actually, I had two thousands RNA-Seq data, I had ran mikado pipeline about half years.

**Comment by lucventurini** [comment] 2019-06-06 18:12
Moving this issue to the next release. I fully intend to fix this, but unfortunately it cannot hold the very belated version 1.5. I will dedicate myself to it as soon as possible.

**Comment by benhg** [comment] 2019-07-27 20:23
I would be happy to take a stab at implementing this, if it would be of use.

**Comment by lucventurini** [comment] 2019-07-29 12:53
@benhg , please, be my guest! The relevant code should be here:

https://github.com/lucventurini/mikado/blob/master/Mikado/serializers/orf.py

**Comment by benhg** [comment] 2019-08-05 01:53
I think I've got something working ... Is there some data I can use to test with? Unfortunately, I'm not super familiar with the codebase.
Thanks,
Ben

**Comment by lucventurini** [comment] 2019-08-05 10:48
Hi @benhg, you can use the public data for the article. You can find it (here)[https://figshare.com/articles/Input_assemblies/5688016]. I would be curious, of course, to see the changes you made!

**Comment by benhg** [comment] 2019-08-05 15:38
I will push it to my fork (and open a PR) as soon as I can verify it works ! I'm too self conscious to push an untested version haha!

**Comment by lucventurini** [comment] 2019-09-04 13:20
Update: after testing on the data for the original article, it appears evident that the bulk of time in serialising the ORFs is spent by calling the BioPython `Bio.Seq.Seq.translate` method. 
This accounts for half of the total time spent by the program serialising the ORFs.
As this is a third party module, there are only two alternatives:
- trying to use multiprocessing to speed up. Due to locking, inter-process communication, etc., this will most probably return quite less than linear speed ups by adding cores.
- Change the method for something more performant.

**Comment by lucventurini** [comment] 2019-09-08 15:34
Dear @shenweima, the latest commit introduces proper multiprocessing for serialising ORFs. I expect it to be more memory hungry as there is the use of a queue, but it should still be very lightweight.

Tomorrow I'll test it with a proper challenging dataset. If it functions, I'll close the issue.

**Comment by lucventurini** [comment] 2019-09-09 09:39
Dear @shenweima, I can confirm that the new method functions. Specifically, now `mikado serialise` can load 954,447 ORFs in just about 3 minutes using 28 parallel processes; at least one minute of this was dedicated to loading the 696,889 transcripts into the "query" table.
Memory was also manageable, with a peak at about 8GBs. 
I will close the issue, which will be completely solved once I merge back everything into `master`.

Again, thank you for reporting and prodding me to solve this long-standing inefficiency. 
@benhg , many thanks for trying to solve this. If you would like to see my final implementation, please see this commit: 335e6a47719ffa94051ab2b041bc47e42402a473. Please ignore the changes to `Mikado/parsers/__init__.py`, I reverted them as inefficient. The rest stands.

**Closed by lucventurini** 2019-09-09 09:39 UTC
Labels: enhancement
