### ISSUE TITLE
Deprecation of _py3k after biopython 1.76 breaks mikado

### ISSUE THREAD

**Issue by jshleap** [EI-CoreBioinformatics/mikado#348] opened 2020-12-22 15:23 UTC
Hello, as your code is now it breaks if is run in anything but python3.6 and biopython<=1.76, when not using conda.

**Comment by lucventurini** [comment] 2020-12-22 15:52
Dear @jshleap 

Thanks for your bug report. The issue you are highlighting is indeed present with Mikado 1.
They are however not present on the most recent versions of the code (see this GitHub) that we plan to bring to PyPI and conda very soon. I have just tried on a virtualenv and the code functions without apparent glitches.

I will close this for now, although we understand that the main source of the problem is the delay in updating the Conda and PyPI packages.

Kind regards,

**Closed by lucventurini** 2020-12-22 15:52 UTC
