### ISSUE TITLE
 intron fraction is null 

### ISSUE THREAD

**Issue by lijing28101** [EI-CoreBioinformatics/mikado#324] opened 2020-08-22 15:24 UTC
Hi, I'm running mikado v2.0rc2. There is no error in mikado prepare and serialise. But it showed the error when I run mikado pick.
```It is impossible that the intron fraction is null when the transcript has at least one intron!```
I checked the pick.log, the last line as below:
```2020-08-21 12:55:30,441 - listener - loci_processer.py:65 - INFO - merge_loci - MainProcess - We have a total of 543099 genes```
But only 2031 genes in mikado.loci.gff3, and only chr1.
What's the error means? What should I do to solve the problem?

Thanks,
Jing

**Comment by lijing28101** [comment] 2020-09-24 19:17
Hi, I find this problem due to padding. 
For the same data, there is no such a bug if I choose no-pad. 
I guess when mikado pad some monoexonic transcripts, it change the transctipt to multiexonic, but still count the intron as 0.
In the pick.log, it shows the total number of genes. But there is no intermediate file for these genes. If there is a bug likes the intron problem, it stops the to write the final file before the problematic gene. Is there any way to check which on has problem?

Thanks,
Jing

**Comment by lucventurini** [comment] 2020-10-13 15:45
Hi @lijing28101 

Apologies for the long delay but I was swamped by another project.

> I guess when mikado pad some monoexonic transcripts, it change the transctipt to multiexonic, but still count the intron as 0.

This should not happen. I will have a look to solve this.

**Comment by lucventurini** [comment] 2020-10-14 16:54
Potential duplicate of #208

**Comment by lucventurini** [comment] 2021-01-18 18:32
Dear @lijing28101 

We have made many changes since the original bug was reported, and cannot reproduce it on our datasets. If it represents again, please reopen the issue.

Kind regards

**Closed by lucventurini** 2021-01-18 18:32 UTC
Labels: bug, duplicate
