### ISSUE TITLE
bed usage? 

### ISSUE THREAD

**Issue by fmarletaz** [EI-CoreBioinformatics/mikado#152] opened 2019-03-01 15:55 UTC
Thanks for developing mikado, really useful tool!  I have a question, I tried to use a bed an input (in `list.txt`) from minimap2 converted with paftools, but I the following error at the `configure` step: 
```
ValueError: Malformed inputs file. Error:
Invalid file name: Leri_isoseq.bed
```

Thanks

Ferdi

**Comment by lucventurini** [comment] 2019-03-01 16:02
Dear @fmarletaz , thank you for your interest in the tool! I think that the problem is that Mikado usually requires BED files to have the extension ".bed12" rather than ".bed". Would you please be able to retry and confirm? Otherwise, I will have to dig into the code a little bit.
If that is the case, I might change the default behaviour to accept ".bed" files as well.

**Comment by fmarletaz** [comment] 2019-03-01 16:09
Just tried, still throw an error. The full error: 
```
2019-03-02 01:05:10,639 - main - __init__.py:124 - ERROR - main - MainProcess - Mikado crashed, cause:
2019-03-02 01:05:10,639 - main - __init__.py:125 - ERROR - main - MainProcess - Malformed inputs file. Error:
Invalid file name: Leri_isoseq.bed12
Traceback (most recent call last):
  File "/home/f/fmarletaz/miniconda2/envs/py36/lib/python3.6/site-packages/Mikado/subprograms/configure.py", line 210, in create_config
    raise ValueError("Invalid file name: {}".format(filename))
ValueError: Invalid file name: Leri_isoseq.bed12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/f/fmarletaz/miniconda2/envs/py36/lib/python3.6/site-packages/Mikado/__init__.py", line 110, in main
    args.func(args)
  File "/home/f/fmarletaz/miniconda2/envs/py36/lib/python3.6/site-packages/Mikado/subprograms/configure.py", line 222, in create_config
    raise ValueError("Malformed inputs file. Error:\n{}".format(exc))
ValueError: Malformed inputs file. Error:
Invalid file name: Leri_isoseq.bed12
```

The bed file looks normal: 
```
Leri_23C        16752996        16798428        cb10569_c33/f2p1/2157/0.998     1000    +       16752996        16798428        0,128,255       17      65,81,113,192,49,95,124,180,87,72,127,161,72,96,117,103,418,    0,8824,10163,12102,13679,18594,22156,26169,29214,31156,33573,34139,36531,39850,40045,44119,45014,
```

Another question incidentally, have you considered writing a tool to use mikado models to add UTRs to existing gene models (e.g. derived from AUGUSTUS), that would avoid having to run PASA, which is never easy... 

Thanks!

**Comment by lucventurini** [comment] 2019-03-01 16:22
Dear @fmarletaz , we are developing at the moment a pipeline to do so, stay tuned on the Augustus front!

Regarding the file type, this looks like a bug. I will have a look into it, most probably early next week though. Thank you for reporting this!

**Comment by lucventurini** [comment] 2019-03-01 21:15
Dear @fmarletaz ,
                              I think there might something wrong in the file list that you give in to Mikado. Would you be able to attach a copy here please?
I will make sure that the error will be more explicative in the next release of Mikado.

**Comment by fmarletaz** [comment] 2019-03-03 05:49
Dear Luca, 
Thanks! I realized that my some space replaced the tabs in my file list, which was causing likely the first error. However, now, I got an error at the prepare stage : 
`2019-03-03 14:13:35,852 - prepare - prepare.py:435 - ERROR - prepare - MainProcess - 'BED12' object has no attribute 'transcript'`.  Thanks again for your help!

**Comment by lucventurini** [comment] 2019-03-04 10:02
Dear @fmarletaz,
                              unfortunately the error is a but too cryptic for me to trace the bug (my fault, Mikado should report the error better). I think it might be due to the formatting of the BED file. While I try to understand where it originated from, I would offer the following possible solutions, in recommendation order:

1- In the pipeline we are developing, there is [a standalone script](https://raw.githubusercontent.com/EI-CoreBioinformatics/ei-annotation/master/eiannot/util/correct_bed12_mappings.py) that should correct the issue with the BED12. This should take care of the issue with the BED12 directly and is probably the preferred solution.
2- In Mikado, there is a script called "bam2gtf.py" (you should have it available among your bash executables already) that converts a BAM into a GTF that will be read correctly by Mikado. Presuming you have your alignments in BAM format, doing:
  ```bam2gtf.py $bam $new_gtf```
  should solve the issue. NOTE: I would download the latest version of the script from [here](https://github.com/EI-CoreBioinformatics/mikado/blob/master/util/bam2gtf.py) rather than using the current version, I recently did some improvements.
3- Also in Mikado, you could try to convert the BED12 to GTF like so:
  ```mikado util convert -of gtf $bed $gtf```

Please let me know whether any of these steps helps!

**Comment by fmarletaz** [comment] 2019-03-05 03:42
Great, thanks for your support, I will try. I actually in the meantime realigned with gmap to get gtf, but I will definitely try these scripts.

**Comment by lucventurini** [comment] 2019-03-08 15:57
Dear @fmarletaz , any update?

**Comment by lucventurini** [comment] 2019-03-19 15:19
Closing for now, to be reopened if new information becomes available.

**Closed by lucventurini** 2019-03-19 15:19 UTC
Labels: bug
