### ISSUE TITLE
Question : Getting rid of redundant transcripts in mikado pick output ? 

### ISSUE THREAD

**Issue by srividya22** [EI-CoreBioinformatics/mikado#331] opened 2020-10-21 14:39 UTC
I am using release version Mikado v2.0rc2. How to get rid of redundant transcripts in the mikado pick output ?
Should we use keep redundant == true during prepare stage. ( as this option language is switched, saw a issue related to that  ) 
**Reduntant transcripts after mikado pick:**
Super-Scaffold_1	mikado	exon	16905	17195	.	+	.	ID=Phygri000001.1.exon1;Parent=Phygri000001.1;
Super-Scaffold_1	mikado	exon	17537	17888	.	+	.	ID=Phygri000001.1.exon2;Parent=Phygri000001.1;
Super-Scaffold_1	mikado	exon	17997	18552	.	+	.	ID=Phygri000001.1.exon3;Parent=Phygri000001.1;

*** discard redundant transcript
Super-Scaffold_1	mikado	exon	16905	17195	.	+	.	ID=Phygri000001.4.exon1;Parent=Phygri000001.4;
Super-Scaffold_1	mikado	exon	17537	17888	.	+	.	ID=Phygri000001.4.exon2;Parent=Phygri000001.4;
Super-Scaffold_1	mikado	exon	17994	18552	.	+	.	ID=Phygri000001.4.exon3;Parent=Phygri000001.4;

 **Highly similar transcripts, Is there a way to polish these RNASeq transcripts the second exon to the same starting point** 
*** discard this
Super-Scaffold_1	mikado	exon	16905	17195	.	+	.	ID=Phygri000001.2.exon1;Parent=Phygri000001.2;
Super-Scaffold_1	mikado	exon	17529	18552	.	+	.	ID=Phygri000001.2.exon2;Parent=Phygri000001.2;

*** Select this one instead of the 3 different transcript as this exon start is already defined in another transcript.
Super-Scaffold_1	mikado	exon	16905	17195	.	+	.	ID=Phygri000001.3.exon1;Parent=Phygri000001.3;
Super-Scaffold_1	mikado	exon	17537	18552	.	+	.	ID=Phygri000001.3.exon2;Parent=Phygri000001.3;

*** discard this 
Super-Scaffold_1	mikado	exon	16905	17195	.	+	.	ID=Phygri000001.5.exon1;Parent=Phygri000001.5;
Super-Scaffold_1	mikado	exon	17541	18552	.	+	.	ID=Phygri000001.5.exon2;Parent=Phygri000001.5;

**Comment by lucventurini** [comment] 2020-10-21 14:56
Dear @srividya22 

Apologies, I am not sure I am understanding the question correctly. Mikado should already discard redundant transcripts in the output; if that is not the case, and you see duplicates, this is a bug.

May I ask you to please post the configuration file for this run?

**Comment by srividya22** [comment] 2020-10-21 15:04
Please find attached the config file, 
[bionano_snakemake.yaml.txt](https://github.com/EI-CoreBioinformatics/mikado/files/5416875/bionano_snakemake.yaml.txt)

**Comment by srividya22** [comment] 2020-10-21 15:23
Sorry If i was not very clear with my question , For the second part,  If there are highly similar intron chains, Is there a way to refine exon start for some transcripts, in the below case the exons of 3 different transcripts have same coordinates except that the second exon start points are different. Instead of producing several alternative spliced transcripts, it is possible to keep one of the transcripts in this case and discard the others.

Exon start 17537 is defined in 2 transcripts and hence more reliable. is it valid to discard the transcripts with Phygri000001.2 , Phygri000001.5 and keep only Phygri000001.3.

First transcript:
Super-Scaffold_1 mikado exon 16905 17195 . + . ID=Phygri000001.1.exon1;Parent=Phygri000001.1;
Super-Scaffold_1 mikado exon **17537** 17888 . + . ID=Phygri000001.1.exon2;Parent=Phygri000001.1;
Super-Scaffold_1 mikado exon 17997 18552 . + . ID=Phygri000001.1.exon3;Parent=Phygri000001.1;

*** discard this
Super-Scaffold_1 mikado exon 16905 17195 . + . ID=Phygri000001.2.exon1;Parent=Phygri000001.2;
Super-Scaffold_1 mikado exon 17529 18552 . + . ID=Phygri000001.2.exon2;Parent=Phygri000001.2;

*** Select this one instead of the 3 different transcript as this exon start is already defined in another transcript.
Super-Scaffold_1 mikado exon 16905 17195 . + . ID=Phygri000001.3.exon1;Parent=Phygri000001.3;
Super-Scaffold_1 mikado exon **17537** 18552 . + . ID=Phygri000001.3.exon2;Parent=Phygri000001.3;

*** discard this
Super-Scaffold_1 mikado exon 16905 17195 . + . ID=Phygri000001.5.exon1;Parent=Phygri000001.5;
Super-Scaffold_1 mikado exon 17541 18552 . + . ID=Phygri000001.5.exon2;Parent=Phygri000001.5;

**Comment by lucventurini** [comment] 2020-10-21 15:36
Dear @srividya22 

OK, now I understand the question better, thank you for clarifying. The short answer is no, currently there is no way to do this. It is however theoretically possible - `mikado compare` can already categorise as "identical" transcripts with very similar splice sites, with some wobble. *Please note that `mikado prepare` is not able to pre-process transcripts in this way, and it is not desirable, as at that point we do not know which are the transcripts to consider as correct.*

I need to discuss with @swarbred and @ljyanesm whether to implement this feature request and how. Please stay tuned.

**Comment by srividya22** [comment] 2020-10-21 16:07
Thanks for the clarification for the second part. But I do see redundant transcripts as well other than highly similar transcripts. Is that a configuration issue ?

**Comment by swarbred** [comment] 2020-10-21 19:29
Dear @srividya22

Just to jump in, mikado prepare doesn't have the behaviour that it looks like you want to achieve. The prepare step as the name suggests prepares the file for the down stream steps in Mikado i.e. serialise and pick. It will perform some checks, remove problematic transcripts and remove those with completely redundant structures i.e. as shown in your first example where the structures are exactly the same between the two transcripts. In the latest miakdo version prepare has a --exclude-redundant flag that defines redundant as the same intron chain i.e. terminal transcript start and end may vary so if you run with this you will exclude more transcripts as redundant. 

What you give in the second example would never be excluded as part of prepare as @lucventurini mentioned (at this point there is no information available to define the "best" model). If you went through the full mikado analysis then the pick stage would score these alternative transcripts and assign the highest scoring as the primary, the other transcripts are output / excluded depending on the choice of configuration but setting max_isoforms = 1 in pick would output only the primary model.

**Comment by lucventurini** [comment] 2020-10-21 20:24
Dear @srividya22

I cannot see anything in the configuration that would push mikado to retain identical transcripts.

The only thing that I can think of would be that the "pad" property is set to true.

However, mikado should get rid of those transcripts automatically even during padding.

Just to test the hypothesis would you please be able to rerun mikado with that switch set to false, please?

**Comment by srividya22** [comment] 2020-10-21 20:54
Thanks @swarbred  and @lucventurini. Sure, I can rerun mikado with pad set to false.

**Comment by lucventurini** [comment] 2020-10-28 15:14
Dear @srividya22 

Did you by any chance manage to rerun mikado without padding? If so and you confirmed that padding introduces duplicates, we can start debugging this.

Kind regards

**Comment by lucventurini** [comment] 2021-01-08 10:35
Closing for now. @srividya22 please let us know if you managed to solve the issue with the recent versions. We cannot confirm the bug on our side.

**Closed by lucventurini** 2021-01-08 10:35 UTC
Labels: enhancement, question
