### ISSUE TITLE
transcript incorrectly identified as non coding (mikado-2.0rc6, mikado-2.0_rc1)

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/mikado#257] opened 2020-01-10 15:26 UTC
Hi @lucventurini  @gemygk 

I am seeing a difference between mikado-2.0rc6_3f62484_CBG and mikado-2.0_rc1 with behaviour that suggests in both versions a transcript with cds features is flagged as non-coding (incorrectly as CDS features are in the prodigal gff) but in the mikado-2.0rc6_3f62484_CBG run this loci is in the final output file with the CDS stripped but in mikado-2.0_rc1 the CDS is retained.

Firstly I should point out the mikado.db was generated with the mikado-2.0_rc1 serialise so if their is a known incompatibility then let me know, however even the mikado-2.0_rc1 pick is flagging this coding loci as non coding

example transcript stringtie_SB2_STRG.143.1

has cds features in prodigal gff mikado_prepared.cds.gf

```
stringtie_SB2_STRG.143.1	Prodigal_v2.6.3	CDS	208	429	1.8	+	0	ID=2710_1;partial=00;start_type=ATG;rbs_motif=None;rbs_spacer=None;gc_cont=0.468;conf=60.40;score=1.84;cscore=3.99;sscore=-2.15;rscore=0.65;uscore=-2.80;tscore=0.00;
```

mikado-2.0_rc1
```
source mikado-2.0_rc1; /usr/bin/time -v mikado pick -p 1 --json-conf configuration_test2.yaml --subloci_out mikado.subloci.gff3 --monoloci_out mikado.monoloci.gff3 --output-dir ./mikado-2.0_rc1_test2 -lv DEBUG --seed 2
```

In final output with CDS features
```
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	mRNA	368224	369413	21	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40;Name=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1;alias=stringtie_SB2_STRG.143.1;fpkm=30;tpm=37;canonical_junctions=1,2,3,4;canonical_number=4;canonical_proportion=1;cds_padded=False;cov=0;padded=True;primary=True
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	368224	368619	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.exon1;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	three_prime_UTR	368224	368579	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.three_prime_UTR1;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	CDS	368580	368619	.	-	1	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.CDS1;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	CDS	368703	368832	.	-	2	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.CDS2;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	368703	368832	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.exon2;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	CDS	368950	369001	.	-	0	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.CDS3;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	368950	369058	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.exon3;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	five_prime_UTR	369002	369058	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.five_prime_UTR1;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	369144	369264	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.exon4;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	five_prime_UTR	369144	369264	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.five_prime_UTR2;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	369385	369413	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.exon5;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	five_prime_UTR	369385	369413	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1.five_prime_UTR3;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G40.1
```
even though pick.log flags the models as non-coding

```
2020-01-10 14:00:54,182 - queue_listener - finalizing.py:124 - DEBUG - _check_cdna_vs_utr - MainProcess - stringtie_SB2_STRG.143.1 is non coding, returning
```

mikado-2.0rc6_3f62484_CBG

```
source mikado-2.0rc6_3f62484_CBG; /usr/bin/time -v mikado pick -p 1 --json-conf configuration_test2.yaml --subloci-out mikado.subloci.gff3 --monoloci-out mikado.monoloci.gff3 --output-dir ./mikado-2.0rc6_3f62484_CBG_test2 -lv DEBUG --seed 2
```
In final output WITHOUT CDS features (ncRNA)

```
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	ncRNA	368251	369413	16.17	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23;fpkm=30;tpm=37;alias=stringtie_SB2_STRG.143.1;canonical_junctions=1,2,3,4;canonical_number=4;canonical_proportion=1;cov=0;primary=True
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	368251	368619	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1.exon1;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	368703	368832	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1.exon2;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	368950	369058	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1.exon3;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	369144	369264	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1.exon4;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1
Uromyces_beticola_EI_v1.1_contig_000006	Mikado_loci	exon	369385	369413	.	-	.	ID=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1.exon5;Parent=mikado.Uromyces_beticola_EI_v1.1_contig_000006G23.1
```
the pick.log agains flags this as non-coding

```
2020-01-10 14:07:22,080 - queue_listener - finalizing.py:125 - DEBUG - _check_cdna_vs_utr - MainProcess - stringtie_SB2_STRG.143.1 is non coding, returning
```
So both versions mark this transcript as non-coding in the log, even though it has an ORF in the prodigal output. But the older mikado-2.0_rc1 version still generates a model with CDS features where mikado-2.0rc6_3f62484_CBG outputs a ncRNA model.

@lucventurini i'm copying the files to
/tgac/workarea/group-ga/Mikado_Test/CB-GENANNO-457_Annotation_Uromyces_beticola

the two pick runs are under dirs

mikado-2.0_rc1_test2
mikado-2.0rc6_3f62484_CBG_test2

Gemy will load this test data to a browser so you can see the difference easily between the two runs.

**Comment by lucventurini** [comment] 2020-01-10 16:34
Hi @swarbred , I am having a look now. It is a bit puzzling, I cannot find any obvious reason of why this should have failed. 
I **think** the problem **might** be upstream, ie the transcript data is not loaded correctly from the database. I am having a look now.

**Comment by lucventurini** [comment] 2020-01-10 17:10
Hi @swarbred, *the problem is in the database*, at least when it comes to the latest release.
If you do a `grep ERROR` in the `pick.log`, you will see a swathe of errors related to the BLAST data being incorrect. 
I can't find the relevant commit(s) right now, but I am pretty sure I solved some bugs related to the loading of BLAST data in the past months.
As such the database is *not* forward-compatible; the latest version of Mikado must be tested with a database generated by the same version.

**Comment by swarbred** [comment] 2020-01-10 18:07
Ok thanks, I can generate the db specific for mikado-2.0rc6_3f62484_CBG and check, however why would the  blast loading change this loci to non-coding ? Or are there also changes to the db that affects the orf loading?

This doesn't explain why mikado-2.0_rc1 also marks this transcript as non coding then outputs a CDS

**Comment by lucventurini** [comment] 2020-01-10 18:29
Hi @swarbred, the problem is that the BLAST results in the database you created are considered in some cases incorrect by the latest version of mikado. This triggers an error that blocks the loading of data for all transcripts in the superlocus - not just the one you are marking for review. Only 316 transcripts out of the over ~700 in the scaffold get the data correctly from the database. This being the situation, I cannot diagnose the bug unless the database is recreated. 

You are correct on the fact that this does not explain the behaviour in the old version of mikado. However, there is the chance that the bug triggered in Mikado 2.0rc1 is solved already in the current version (especially given that there is about half a year of development, or more, between the two versions). Before digging in the old code, I would rather confirm that the bug is still present in our current version of the program.

**Comment by swarbred** [comment] 2020-01-10 19:22
@lucventurini 
actually is the pick log message just indicating the transcript is non coding in the gtf and not suggesting no orf info. If thats the case thre is no issue.

**Comment by lucventurini** [comment] 2020-01-13 10:34
> @lucventurini
> actually is the pick log message just indicating the transcript is non coding in the gtf and not suggesting no orf info. If thats the case thre is no issue.

Hi @swarbred , that is indeed the case for version 2.0rc1. The GFF3 shows that the model has had its CDS correctly loaded.

As a side note, I guess that this issue points to the need of using a database generated with the latest version of Mikado for the tests.

I will close the issue for now, please reopen it if you see again this problem.

**Closed by lucventurini** 2020-01-13 10:34 UTC
Labels: bug
