### ISSUE TITLE
Error while running configuration

### ISSUE THREAD

**Issue by sagnikbanerjee15** [EI-CoreBioinformatics/mikado#124] opened 2018-07-30 13:54 UTC
Hello,

I am currently running the following command "mikado configure --list mikado_list_file --reference ../genome/Zea_mays.AGPv4.dna.toplevel.fa --mode permissive --scoring plant.yaml --copy-scoring plants.yaml -bt uniprot_sprot_plants.fasta configuration.yaml" but I am running into the following error.

2018-07-30 08:47:51,697 - to_json - configurator.py:567 - ERROR - check_json - MainProcess - (<class 'dict'>, <class 'NoneType'>)
Traceback (most recent call last):
  File "/home/sagnik/.local/lib/python3.6/site-packages/Mikado/configuration/configurator.py", line 533, in check_json
    (type(json_conf), type(scoring))
AssertionError: (<class 'dict'>, <class 'NoneType'>)
2018-07-30 08:47:51,698 - to_json - configurator.py:614 - ERROR - to_json - MainProcess - (<class 'dict'>, <class 'NoneType'>)
Traceback (most recent call last):
  File "/home/sagnik/.local/lib/python3.6/site-packages/Mikado/configuration/configurator.py", line 612, in to_json
    json_dict = check_json(json_dict, simple=simple, logger=logger)
  File "/home/sagnik/.local/lib/python3.6/site-packages/Mikado/configuration/configurator.py", line 533, in check_json
    (type(json_conf), type(scoring))
AssertionError: (<class 'dict'>, <class 'NoneType'>)
Traceback (most recent call last):
  File "/home/sagnik/.local/lib/python3.6/site-packages/Mikado/configuration/configurator.py", line 612, in to_json
    json_dict = check_json(json_dict, simple=simple, logger=logger)
  File "/home/sagnik/.local/lib/python3.6/site-packages/Mikado/configuration/configurator.py", line 533, in check_json
    (type(json_conf), type(scoring))
AssertionError: (<class 'dict'>, <class 'NoneType'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sagnik/.local/bin/mikado", line 11, in <module>
    load_entry_point('Mikado==1.2.2', 'console_scripts', 'mikado')()
  File "/opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/py-setuptools-35.0.2-kvj5vuzczq4idwn7rlmg6vzklttwwpgy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/py-setuptools-35.0.2-kvj5vuzczq4idwn7rlmg6vzklttwwpgy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/py-setuptools-35.0.2-kvj5vuzczq4idwn7rlmg6vzklttwwpgy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/opt/rit/spack-app/linux-rhel7-x86_64/gcc-4.8.5/py-setuptools-35.0.2-kvj5vuzczq4idwn7rlmg6vzklttwwpgy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sagnik/.local/lib/python3.6/site-packages/Mikado/__init__.py", line 28, in <module>
    from . import loci
  File "/home/sagnik/.local/lib/python3.6/site-packages/Mikado/loci/__init__.py", line 13, in <module>
    from .abstractlocus import Abstractlocus
  File "/home/sagnik/.local/lib/python3.6/site-packages/Mikado/loci/abstractlocus.py", line 33, in <module>
    json_conf = to_json(None)
  File "/home/sagnik/.local/lib/python3.6/site-packages/Mikado/configuration/configurator.py", line 616, in to_json
    errored.write(open(string).read())
FileNotFoundError: [Errno 2] No such file or directory: '/work/LAS/rpwise-lab/sagnik/data/maize/AGPv4/transcriptome/mikado.json'

Could you please help with that?

**Comment by lucventurini** [comment] 2018-11-01 16:09
Dear @sagnikbanerjee15 ,
                                                thank you for reporting the bug. I can reproduce it on the development branch of Mikado. I will look into it ASAP.

Many apologies for the late reply, this year I have been in the process of moving cities and getting married, which unfortunately meant I did not see this bug until now.

**Comment by lucventurini** [comment] 2018-11-01 16:19
Dear @sagnikbanerjee15 ,
                                             the bug is caused by an empty / invalid "plants.yaml" file within your working directory. Removing it should negate the bug.

I will work on the bug so that it is solved by the next release.

**Comment by lucventurini** [comment] 2018-11-02 14:37
Dear @sagnikbanerjee15 ,
                                                 the bug is now fixed and will be absent from the next release of Mikado (1.3).

Thank you for reporting it, and apologies again for the late response.

Kind regards

**Closed by lucventurini** 2018-11-02 14:37 UTC
Labels: bug

**Comment by sagnikbanerjee15** [comment] 2018-11-02 16:50
Thank you @lucventurini for your help.
