### ISSUE TITLE
Mikado.test() fails: how to resolve the "sqlite3.OperationalError: disk I/O error"

### ISSUE THREAD

**Issue by zebrafish-507** [EI-CoreBioinformatics/mikado#172] opened 2019-05-02 08:46 UTC
I installed mikado and all the dependencies using anconda. I tested the installed modules by:
>>  import Mikado
>>  Mikado.test()
The error message I always got is:
">>> import Mikado
/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/Mikado/configuration/configurator.py:529: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  scoring = yaml.load(scoring_file)
>>> Mikado.test()
Running unit tests for Mikado
NumPy version 1.16.3
NumPy relaxed strides checking option: True
NumPy is installed in /newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/numpy
Python version 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
nose version 1.3.7
...................................................................................................................TAA
....................E.EE...............................................['permissive', 'split']
..2019-05-02 16:33:46,029 - main - __init__.py:124 - ERROR - main - MainProcess - Mikado crashed, cause:
2019-05-02 16:33:46,029 - main - __init__.py:125 - ERROR - main - MainProcess - (sqlite3.OperationalError) disk I/O error
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 361, in connect
    return _ConnectionFairy._checkout(self, self._fairy)
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 344, in _do_get
    c = self._create_connection()
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 651, in __connect
    pool.dispatch.connect(self.connection, self)
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/newlustre/home/longyong/anaconda3/lib/python3.6/site-packages/Mikado/utilities/dbutils.py", line 109, in set_sqlite_pragma
    cursor.execute("PRAGMA synchronous=OFF")
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:"
How can I resolve this error?

**Comment by lucventurini** [comment] 2019-05-02 11:10
Dear @zebrafish-507, 
                                    thank you for using our program and for reporting this bug. From a quick search, the problem that you are encountering seems to be something that could happen on NFS systems, although to be honest, I have not seen it happening on our cluster environments.
In any case, I will add a try-except clause to this to avoid the locking.

**Comment by lucventurini** [comment] 2019-05-02 11:23
Dear @zebrafish-507 , I have uploaded the potential fix in the latest commit in the development branch (6113045). If you could please test it, I would be able to confirm the fix.

**Comment by zebrafish-507** [comment] 2019-05-02 13:48
Thanks! @Luca,
I replaced the old compare.py and dbutils.py files with the new ones, where should I put the setup.cfg file. There was no folder named "mikado" in the path.

**Comment by lucventurini** [comment] 2019-05-02 14:11
Dear @zebrafish-507, 
                                    the setup.cfg should not be necessary for your user case. **Please use the anaconda version of compare.py**, I have worked extensively on that part of the code since I uploaded the latest version to Anaconda, the new one most probably will break all sorts of stuff! Apologies for having lumped that file as well into the commit.

I hope the new dbutils.py will solve your issue.

Kind regards

**Comment by zebrafish-507** [comment] 2019-05-02 15:17
Dear @lucventurini,
I re-installed Mikado and ran the test. The I/O error still existed. See blow for the error message:

dbapi_connection = <sqlite3.Connection object at 0x7fd79b4bff10>
connection_record = <sqlalchemy.pool.base._ConnectionRecord object at 0x7fd789580dd8>

    @event.listens_for(Engine, "connect")
    def set_sqlite_pragma(dbapi_connection, connection_record):
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
>       cursor.execute("PRAGMA synchronous=OFF")
E       sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
E       (Background on this error at: http://sqlalche.me/e/e3q8)

connection_record = <sqlalchemy.pool.base._ConnectionRecord object at 0x7fd789580dd8>
cursor     = <sqlite3.Cursor object at 0x7fd78a5b4e30>
dbapi_connection = <sqlite3.Connection object at 0x7fd79b4bff10>

anaconda3/lib/python3.6/site-packages/Mikado-1.5-py3.6-linux-x86_64.egg/Mikado/utilities/dbutils.py:109: OperationalError

Best regards,

**Comment by lucventurini** [comment] 2019-05-02 15:36
Dear @zebrafish-507 , would the error persist if you installed only the updated `dbutils.py` file from the previous commit? That file contains the patch.

Kind regards

**Comment by zebrafish-507** [comment] 2019-05-03 03:01
Dear @lucventurini,
I re-installed mikado by git clone and by downloading the 1.3beta version, but the I/O error was always encountered. It said like this:
..2019-05-03 10:54:50,548 - main - __init__.py:124 - ERROR - main - MainProcess - Mikado crashed, cause:
2019-05-03 10:54:50,548 - main - __init__.py:125 - ERROR - main - MainProcess - (sqlite3.OperationalError) disk I/O error
(Background on this error at: http://sqlalche.me/e/e3q8)
Can you figure out what's wrong?
Best,

**Comment by lucventurini** [comment] 2019-05-03 08:55
Dear @zebrafish-507, apologies for not being clear enough in the previous message.

The fix is present in the development branch of my personal fork (https://github.com/lucventurini/mikado), specifically this file:

https://raw.githubusercontent.com/lucventurini/mikado/development/Mikado/utilities/dbutils.py

There are two options:
- install the github development version from the fork. I have made a lot of changes, though (please see the changelog). They mostly make the program better, and I have had everything fully tested, but still, it is the development branch. 
- patch the Mikado/utilities/dbutils.py file using the version from above. I had not touched that section of the codebase in years before yesterday, so plugging it in the new code should not cause any bug to emerge. 

Regarding why the bug appears in the first place, I unfortunately cannot diagnose it from here. It looks like a problem with your disk, potentially triggered by NFS. I hope that the patch will provide a workaround. 

Thank you for your patience. 

Kind regards

**Comment by zebrafish-507** [comment] 2019-05-04 00:28
Dear @lucventurini,
I re-installed mikado according to your instructions, but couldn't resolve the problem as well. It is possible that there are some problems with our disk. I'll ask our manager for help. Thanks a lot.
Best,

**Comment by lucventurini** [comment] 2019-05-09 13:36
Dear @zebrafish-507 ,
                                       I have had a long look at unit-tests today. I am not sure it is your case, but the bug you triggered might have been a case of Mikado trying to overwrite some of the installation files when doing the tests. I should have now fixed the issue - I was testing for exactly such a scenario. Potentially this could solve your issue as well (although I caution that I was still not able to reproduce your exact bug).

If you could install from the https://github.com/lucventurini/mikado/ repository (development branch) we could verify whether this fixes the issue - unless you and your system manager found the issue to be originating in something specific of your system.

Kind regards

**Comment by lucventurini** [comment] 2019-05-16 13:08
Dear @zebrafish-507 ,
                                        any news on this front?

**Comment by zebrafish-507** [comment] 2019-05-16 13:59
Dear @lucventurini, 
Sorry. I couldn't address this issue by reinstalling mikado. Our system manager had no idea about this I/O error as well. I'm wondering if mikado can work well with real data despite of this test error.

**Comment by lucventurini** [comment] 2019-05-16 15:24
Dear @zebrafish-507, 
                                        A way to test it is to install, then clone from github, go into sample_data, and launch snakemake. The mini test pipeline will also need diamond and prodigal to be installed. 
If that functions, it's probably some kind of obscure error in the tests, that I'm trying to catch and fix but that will not affect the program.

**Comment by lucventurini** [comment] 2019-06-05 12:56
Closing for the time being.

**Closed by lucventurini** 2019-06-05 12:56 UTC
Labels: bug
