### ISSUE TITLE
EI:Internal mikado compare dies trying to treat an int-value with __getitem__()

### ISSUE THREAD

**Issue by cschu** [EI-CoreBioinformatics/mikado#174] opened 2019-05-09 17:31 UTC
Debug information below. This worked fine with a 1.5 version from <20th February (unfortunately we didn't have a show_commit_hash back then), contained in /ei/software/testing/gmc/dev/x86_64/mikado.simg

**cwd:**
/ei/workarea/group-pb/schudomc_sandbox/gmc_dev/testdata_MAZ

**command line:** 
singularity exec /ei/software/testing/mikado/20190325_c940de1/x86_64/mikado-20190325_c940de1.simg mikado compare --exclude-utr --extended-refmap -r gmc_run/mikado_prepared.gtf -p /ei/workarea/group-pb/schudomc_sandbox/gmc_dev/testdata_MAZ/external_metrics/proteins/Woodland_Strawberry_protein.80cov60id.gff -o gmc_run/generate_metrics/mikado_compare/proteins/Woodland_Strawberry_protein_80cov_60id/mikado_Woodland_Strawberry_protein_80cov_60id

**Error message from** gmc_run/logs/gmc_run.mikado_compare.prot.Woodland_Strawberry_protein_80cov_60id.log

2019-05-09 15:27:19,630 - main_queue - compare.py:638 - ERROR - compare - MainProcess - 'int' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/conda/lib/python3.6/site-packages/Mikado/scales/compare.py", line 636, in compare
    parse_prediction(args, genes, positions, queue_logger)
  File "/usr/local/conda/lib/python3.6/site-packages/Mikado/scales/compare.py", line 407, in parse_prediction
    printout_tmap=True)
  File "/usr/local/conda/lib/python3.6/site-packages/Mikado/scales/assigner.py", line 130, in __init__
    self.__load_from_results(results)
  File "/usr/local/conda/lib/python3.6/site-packages/Mikado/scales/assigner.py", line 147, in __load_from_results
    self.stat_calculator.merge_into(stat_calculator)
  File "/usr/local/conda/lib/python3.6/site-packages/Mikado/scales/accountant.py", line 520, in merge_into
    if ic_key not in self.intron_chains[chrom][strand]:
TypeError: 'int' object is not subscriptable

**Comment by lucventurini** [comment] 2019-05-09 20:10
Thanks for reporting, I will have a look at it ASAP!

**Comment by lucventurini** [comment] 2019-05-09 22:24
Hi @cschu ,
                       actually this might have already been solved some time ago, you are testing with an old version of the code (you can berate me for coding so much another time!). You can try the latest version (mikado-20190509_2e86e93), hopefully the bug has already been fixed.

**Comment by cschu** [comment] 2019-05-09 23:34
Thanks @lucventurini, I'll try that tomorrow.

**Comment by lucventurini** [comment] 2019-05-16 13:07
Hi @cschu ,
                      did you confirm whether the issue is fixed in more recent developments?

**Comment by cschu** [comment] 2019-05-20 01:13
Hi @lucventurini,

It seems to be fixed for mikado compare, but not for mikado pick:

Mikado version/container:  /ei/software/testing/mikado/20190513_8134a3c/x86_64/mikado-20190513_8134a3c.img 

CWD: /ei/workarea/group-pb/schudomc_sandbox/gmc_dev/testdata_MAZ

mikado pick log: gmc_run7/hpc_logs/20190517_151345gmc_mikado_pick21202571_t128n8.slurm.log (first exception see below)

Error occurs with any metric, not just the named kallisto_tpm (i.e. if I take the kallisto metrics out, it will die with another.)

Let me know if you need more data.

Command: singularity exec /ei/software/testing/mikado/20190513_8134a3c/x86_64/mikado-20190513_8134a3c.img mikado pick -od gmc_run7 --procs 30
 --json-conf gmc_run7/gmc_run.mikado_config.yaml --subloci_out $(basename gmc_run7/mikado.subloci.gff3) gmc_run7/mikado_prepared.gtf

Process LociProcesser-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Mikado/loci/abstractlocus.py", line 1213, in _calculate_score
    metrics = dict((tid, rgetattr(self.transcripts[tid], param)[0]) for tid in self.transcripts)
  File "/usr/local/lib/python3.6/site-packages/Mikado/loci/abstractlocus.py", line 1213, in <genexpr>
    metrics = dict((tid, rgetattr(self.transcripts[tid], param)[0]) for tid in self.transcripts)
TypeError: 'int' object is not subscriptable

**Comment by lucventurini** [comment] 2019-05-20 08:21
Hi @cschu ,
                     thanks for reporting. This is a similar type of bug but in a completely different section of the code, hence I am not surprised it was not fixed by my updates. I will have a look as soon as I can.

**Comment by lucventurini** [comment] 2019-05-22 09:49
Hi @cschu ,
                      I think that the problem might be that the external metrics have not been specified with an "external." string. I cannot verify this at the moment because I am shut out of the NBI cluster. You can try to modify the file `Mikado/loci/abstractlocus.py` in this way at line 1213:

```python
        else:
            metrics = dict((tid, getattr(self.transcripts[tid], param)) for tid in self.transcripts)
```

becomes:

```python
        else:
            try:
                metrics = dict((tid, getattr(self.transcripts[tid], param)) for tid in self.transcripts)
            except (TypeError, IndexError):
                raise TypeError("Invalid metric: {}".format(param))
```

This should give us some pointers to the problem. I cannot update the code directly because I was working on another issue and therefore it would be a bit messy to pull from the development branch (yes, I should start being more tidy .... )

**Comment by lucventurini** [comment] 2019-05-26 14:36
Update: the problem is caused by mikado not finding the correct external metrics in the database, and crashing. Fix under way.

**Comment by lucventurini** [comment] 2019-05-31 11:59
@cschu now Mikado pick will **require** a database to proceed. It should also try hard to find the database if needed.
This should avoid a repeat of the first bug.

**Comment by lucventurini** [comment] 2019-06-06 18:10
Tested by @cschu, I think at it can be safely closed for now.

**Closed by lucventurini** 2019-06-06 18:10 UTC
Labels: EI-Internal, bug
