### ISSUE TITLE
sqlite3.IntegrityError during mikado serialise with blast homology

### ISSUE THREAD

**Issue by JulienPPichon** [EI-CoreBioinformatics/mikado#422] opened 2021-11-01 13:54 UTC
Hello,

I am using mikado on two GTF files coming from RNAseq and ISOseq reads and a new genome assembly with HiFiasm, with spliced junctions produced by Portcullis and 2passtools, transdecoder to predict ORFs and blast homology. Everything is working fine until the serialise step where I have the following error:

`2021-10-29 10:00:56,630 - serialise - orf.py:351 - INFO - __serialize_single_thread - MainProcess - Finished loading 270910 ORFs into the database
2021-10-29 10:00:58,598 - serialise - serialise.py:187 - INFO - load_orfs - MainProcess - Finished loading ORF data
2021-10-29 10:00:58,630 - serialise - serialise.py:142 - INFO - load_blast - MainProcess - Starting to load BLAST data
2021-10-29 10:00:58,630 - serialise - blast_serialiser.py:82 - INFO - __init__ - MainProcess - Number of dedicated workers: 1
2021-10-29 10:01:02,458 - serialise - blast_serialiser.py:249 - INFO - __serialize_targets - MainProcess - Started to serialise the targets
2021-10-29 10:01:02,918 - serialise - blast_serialiser.py:283 - INFO - __serialize_targets - MainProcess - Loaded 108083 objects into the "target" table
2021-10-29 10:01:03,140 - serialise - blast_serialiser.py:174 - INFO - __serialize_queries - MainProcess - Started to serialise the queries
2021-10-29 10:01:03,295 - serialise - blast_serialiser.py:226 - INFO - __serialize_queries - MainProcess - Loaded 0 objects into the "query" table
2021-10-29 10:01:03,938 - serialise - blast_serialiser.py:233 - INFO - __serialize_queries - MainProcess - 257889 in queries
2021-10-29 10:01:04,847 - serialise - tabular_utils.py:431 - INFO - parse_tab_blast - MainProcess - Reading mikado_prepared.blast.tsv data
2021-10-29 10:01:39,726 - serialise - tabular_utils.py:481 - INFO - parse_tab_blast - MainProcess - Finished reading mikado_prepared.blast.tsv data, starting serialisation in single-threaded mode
2021-10-29 10:17:05,615 - serialise - utils.py:48 - CRITICAL - load_into_db - MainProcess - Failed to serialise BLAST!
2021-10-29 10:17:05,615 - serialise - utils.py:49 - ERROR - load_into_db - MainProcess - (sqlite3.IntegrityError) UNIQUE constraint failed: hsp.query_id, hsp.target_id, hsp.query_hsp_start, hsp.query_hsp_end, hsp.target_hsp_start, hsp.target_hsp_end
[SQL: INSERT INTO hsp (counter, query_id, target_id, query_hsp_start, query_hsp_end, query_frame, target_hsp_start, target_hsp_end, target_frame, "match", hsp_evalue, hsp_bits, hsp_identity, hsp_positives, hsp_length) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [(1, 1, 48122, 11, 737, 3.0, 509, 749.0, 0, '|||||||||++///++|||/||/|/|+|||||||/|+||/|||+|||+||++|/|||+/||/|+|/+|||||//|______+||/----/|++||+|/||||||/|/|||||||||||+++|+/+/|||/||||+|+|//+++||/||||//|+///|||/|||///|+/||/|||+///|//|||+|+|+//||/+||+/++/++/|+|//++|++////||+///+/|/+++/+//|+|+++|/', 1.34e-49, 176.0, 48.78048780487805, 70.73170731707317, 246), (1, 1, 51469, 11, 737, 3.0, 502, 742.0, 0, '|||||||||++////+|||/||/|/|+|||||||/|+||/|||+|||+||++|/|||+/|//|+|/+|||||//|/+//+__////+|+||||/||||||/|/|||||||||||+++|+/+/|/|/+|||+|++//+++|/|||||//|+//+|||/|||///|//||/|||+///|///|++|+|+//||/+||+/++/++/|+|//+/|/+////||+/////|/+|+/+//|+|+|++/', 5.77e-45, 162.0, 47.107438016528924, 68.59504132231406, 242), (1, 1, 51471, 377, 737, 3.0, 0, 120.0, 0, '|||/+|||+|++///++|/|||||//|+//+|||/|||///|/|||/|||+///|///||+|+|+//||/+||+/++/++/|+|//++|/+////||+/////|/+|+++//|+|+|++/', 3.29e-13, 70.5, 38.333333333333336, 64.16666666666667, 120), (1, 1, 75057, 230, 644, 3.0, 669, 805.0, 0, '||||/|+/|/|/+/+|_____________/|//+|///+/|+|+|//||+/|///++/+|///|__|+|-|+/////||/|+|||/--//|////|/|////+/+/+|------+|+|/|----||||/|||+|///++|/|||+///||+', 2.4, 31.6, 31.788079470198678, 47.682119205298015, 151), (1, 2, 37373, 1766, 2102, 3.0, 309, 435.0, 0, '|/++//|||//+/|||/|+//+|++|//|/|||///|//|+|/|+/////+|//|/-------+|//|++|+||-----|//+|+/|+--+|//++/|////////|++/+++|/+|/|+/++|/|', 9.5, 32.0, 28.57142857142857, 51.587301587301596, 126), (1, 2, 48122, 11, 2558, 3.0, 509, 1381.0, 0, '|||||||||++///++|||/||/|/|+|||||||/|+||/|||+|||+||++|/|||+/||/|+|/+|||||//|______+||/----/|++||+|/||||||/|/|||||||||||+++|+/+/|||/||||+|+|//+++||/||| ... (594 characters truncated) ... +/|/||||/|+||/||+|+//||+||||/||//||/|/+/|/+||||/|||||||+||//++///|/+++//|//+/||+//_|/|/++||++||||||||+||||++||/||+/|/|+|////+/|+/|+//||/+||||-|//+/||', 3.43e-155, 499.0, 42.600896860986545, 64.34977578475336, 892), (1, 2, 51469, 11, 2636, 3.0, 502, 1397.0, 0, '|||||||||++////+|||/||/|/|+|||||||/|+||/|||+|||+||++|/|||+/|//|+|/+|||||//|/+//+__////+|+||||/||||||/|/|||||||||||+++|+/+/|/|/+|||+|++//+++|/|||||//| ... (614 characters truncated) ... |||/||//||||///|/++|||//|||||//||//++///|/+++//|//|/+|///_|/|/++||++||||||||+||||++||/|||/|/|+|///++/|+/|+//||/+||||||/||/|+||+|||+/|/+||||/|//+/|+/+', 1.41e-159, 511.0, 41.33771929824561, 63.377192982456144, 912), (1, 2, 51471, 377, 2636, 3.0, 0, 721.0, 0, '|||/+|||+|++///++|/|||||//|+//+|||/|||///|/|||/|||+///|///||+|+|+//||/+||+/++/++/|+|//++|/+////||+/////|/+|+++//|+|+|++/+//++++|+||///+//|+/|/++++||+ ... (481 characters truncated) ... |||/||//||||/+/|/++|||//||+||//||//+////|/+++//+//|/+|///_|/|/++||++||||||||+||||++|///||/|/|+|////+/|++|+//||/+|+||||/||/|+||+|/|+/|/+||||/|//+/|+++', 2.9399999999999996e-94, 318.0, 34.017971758664956, 56.867779204107826, 779)  ... displaying 10 of 2765300 total bound parameter sets ...  (23, 257888, 105261, 358, 757, 2.0, 379, 512.0, 0, '+|+|||||/|//|/+/||||//|//|+|/||||||//|/||/|/|////+|///|///|||+/+/|+/|/|//+//|/|//||/||+/|//+/|////|+|/+///|//||/||+////+/|+/|/|/|//+|', 1.23e-20, 98.2, 40.6015037593985, 53.383458646616546, 133), (26, 257888, 105261, 313, 598, 2.0, 560, 655.0, 0, '|//+/|//+//////+|+|||||/|//|/+/||////|//|++/|/||||/+|//|/+/|////||///+////||/////////|///|/|/|/', 3.97e-06, 52.0, 31.57894736842105, 42.10526315789473, 95)]]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1751, in _execute_context
    self.dialect.do_executemany(
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 714, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: hsp.query_id, hsp.target_id, hsp.query_hsp_start, hsp.query_hsp_end, hsp.target_hsp_start, hsp.target_hsp_end

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/julien/.local/lib/python3.9/site-packages/Mikado/serializers/blast_serializer/utils.py", line 40, in load_into_db
    self.engine.execute(self.hsp_i_string, hsps)
  File "<string>", line 2, in execute
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3108, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1248, in execute
    return self._exec_driver_sql(
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1547, in _exec_driver_sql
    ret = self._execute_context(
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1751, in _execute_context
    self.dialect.do_executemany(
  File "/home/julien/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 714, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: hsp.query_id, hsp.target_id, hsp.query_hsp_start, hsp.query_hsp_end, hsp.target_hsp_start, hsp.target_hsp_end
[SQL: INSERT INTO hsp (counter, query_id, target_id, query_hsp_start, query_hsp_end, query_frame, target_hsp_start, target_hsp_end, target_frame, "match", hsp_evalue, hsp_bits, hsp_identity, hsp_positives, hsp_length) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [(1, 1, 48122, 11, 737, 3.0, 509, 749.0, 0, '|||||||||++///++|||/||/|/|+|||||||/|+||/|||+|||+||++|/|||+/||/|+|/+|||||//|______+||/----/|++||+|/||||||/|/|||||||||||+++|+/+/|||/||||+|+|//+++||/||||//|+///|||/|||///|+/||/|||+///|//|||+|+|+//||/+||+/++/++/|+|//++|++////||+///+/|/+++/+//|+|+++|/', 1.34e-49, 176.0, 48.78048780487805, 70.73170731707317, 246), (1, 1, 51469, 11, 737, 3.0, 502, 742.0, 0, '|||||||||++////+|||/||/|/|+|||||||/|+||/|||+|||+||++|/|||+/|//|+|/+|||||//|/+//+__////+|+||||/||||||/|/|||||||||||+++|+/+/|/|/+|||+|++//+++|/|||||//|+//+|||/|||///|//||/|||+///|///|++|+|+//||/+||+/++/++/|+|//+/|/+////||+/////|/+|+/+//|+|+|++/', 5.77e-45, 162.0, 47.107438016528924, 68.59504132231406, 242), (1, 1, 51471, 377, 737, 3.0, 0, 120.0, 0, '|||/+|||+|++///++|/|||||//|+//+|||/|||///|/|||/|||+///|///||+|+|+//||/+||+/++/++/|+|//++|/+////||+/////|/+|+++//|+|+|++/', 3.29e-13, 70.5, 38.333333333333336, 64.16666666666667, 120), (1, 1, 75057, 230, 644, 3.0, 669, 805.0, 0, '||||/|+/|/|/+/+|_____________/|//+|///+/|+|+|//||+/|///++/+|///|__|+|-|+/////||/|+|||/--//|////|/|////+/+/+|------+|+|/|----||||/|||+|///++|/|||+///||+', 2.4, 31.6, 31.788079470198678, 47.682119205298015, 151), (1, 2, 37373, 1766, 2102, 3.0, 309, 435.0, 0, '|/++//|||//+/|||/|+//+|++|//|/|||///|//|+|/|+/////+|//|/-------+|//|++|+||-----|//+|+/|+--+|//++/|////////|++/+++|/+|/|+/++|/|', 9.5, 32.0, 28.57142857142857, 51.587301587301596, 126), (1, 2, 48122, 11, 2558, 3.0, 509, 1381.0, 0, '|||||||||++///++|||/||/|/|+|||||||/|+||/|||+|||+||++|/|||+/||/|+|/+|||||//|______+||/----/|++||+|/||||||/|/|||||||||||+++|+/+/|||/||||+|+|//+++||/||| ... (594 characters truncated) ... +/|/||||/|+||/||+|+//||+||||/||//||/|/+/|/+||||/|||||||+||//++///|/+++//|//+/||+//_|/|/++||++||||||||+||||++||/||+/|/|+|////+/|+/|+//||/+||||-|//+/||', 3.43e-155, 499.0, 42.600896860986545, 64.34977578475336, 892), (1, 2, 51469, 11, 2636, 3.0, 502, 1397.0, 0, '|||||||||++////+|||/||/|/|+|||||||/|+||/|||+|||+||++|/|||+/|//|+|/+|||||//|/+//+__////+|+||||/||||||/|/|||||||||||+++|+/+/|/|/+|||+|++//+++|/|||||//| ... (614 characters truncated) ... |||/||//||||///|/++|||//|||||//||//++///|/+++//|//|/+|///_|/|/++||++||||||||+||||++||/|||/|/|+|///++/|+/|+//||/+||||||/||/|+||+|||+/|/+||||/|//+/|+/+', 1.41e-159, 511.0, 41.33771929824561, 63.377192982456144, 912), (1, 2, 51471, 377, 2636, 3.0, 0, 721.0, 0, '|||/+|||+|++///++|/|||||//|+//+|||/|||///|/|||/|||+///|///||+|+|+//||/+||+/++/++/|+|//++|/+////||+/////|/+|+++//|+|+|++/+//++++|+||///+//|+/|/++++||+ ... (481 characters truncated) ... |||/||//||||/+/|/++|||//||+||//||//+////|/+++//+//|/+|///_|/|/++||++||||||||+||||++|///||/|/|+|////+/|++|+//||/+|+||||/||/|+||+|/|+/|/+||||/|//+/|+++', 2.9399999999999996e-94, 318.0, 34.017971758664956, 56.867779204107826, 779)  ... displaying 10 of 2765300 total bound parameter sets ...  (23, 257888, 105261, 358, 757, 2.0, 379, 512.0, 0, '+|+|||||/|//|/+/||||//|//|+|/||||||//|/||/|/|////+|///|///|||+/+/|+/|/|//+//|/|//||/||+/|//+/|////|+|/+///|//||/||+////+/|+/|/|/|//+|', 1.23e-20, 98.2, 40.6015037593985, 53.383458646616546, 133), (26, 257888, 105261, 313, 598, 2.0, 560, 655.0, 0, '|//+/|//+//////+|+|||||/|//|/+/||////|//|++/|/||||/+|//|/+/|////||///+////||/////////|///|/|/|/', 3.97e-06, 52.0, 31.57894736842105, 42.10526315789473, 95)]]
(Background on this error at: https://sqlalche.me/e/14/gkpj)`

The previous assembly of the genome is still working great with the same environment and dependencies. I checked the integrity of the new fasta file with seqkit and no sign of unusual characters.

Best regards,
Julien

**Comment by swarbred** [comment] 2021-11-01 14:33
HI @JulienPPichon 

Can you confirm the blast/diamond homology data was generated using the prepare fasta output and using --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore ppos btop

**Comment by JulienPPichon** [comment] 2021-11-01 14:37
Hi @swarbred 

Yes exactly

**Comment by swarbred** [comment] 2021-11-01 16:20
HI @JulienPPichon

From the error it appears hsp (counter, query_id, target_id, query_hsp_start, query_hsp_end, query_frame, target_hsp_start, target_hsp_end, target_frame, "match", hsp_evalue, hsp_bits, hsp_identity, hsp_positives, hsp_length) is not unique, i.e. you have the same query matching the same target more than once, have you combined outputs from multiple blast/diamond searches or have a blast db with a duplicated target?

**Comment by JulienPPichon** [comment] 2021-11-01 17:19
I see I don't know where it could come in the upstream pipeline because I used same parameters. Maybe filter the blast output from mikado would be the easiest. I use the same metazoan swissprot database that from the previous genome assembly run.
I looked at the blast tsv output and saw a lot of reads having the same combined first (query_id) and second (target_id) column, but it does not give an error for the previous genome assembly. What combined columns should be unique ?

Best regards,

**Comment by swarbred** [comment] 2021-11-01 18:46
HI @JulienPPichon 

The constraint is on 
hsp.query_id, hsp.target_id, hsp.query_hsp_start, hsp.query_hsp_end, hsp.target_hsp_start, hsp.target_hsp_end

**Comment by JulienPPichon** [comment] 2021-11-02 10:31
Hi @swarbred 

No sign of duplicates in the blast tsv output, in the database or in the mikado_prepared fasta file. Any ideas of what file I can check now ?

Best,

**Comment by ljyanesm** [comment] 2021-11-02 12:46
Dear @JulienPPichon,

Could you share the inputs to `serialise` with us? I would like to have a reproducible example from your data.

Kindly,
Luis.

**Comment by JulienPPichon** [comment] 2021-11-02 14:32
Hi @ljyanesm 

`mikado serialise --json-conf configuration.yaml --xml mikado_prepared.blast.tsv --orfs mikado_prepared.fasta.transdecoder.gff3 --blast_targets /scratchdata/julien/blast_database/metazoan_swissprot/uniprot_sprot.fasta --junctions /scratchdata/julien/final_annotation/portcullis/filter/portcullis.pass.junctions.bed,/scratchdata/julien/final_annotation/2passtools/hq_transcripts_junc_filtered12.bed`

Which data do you need? Unfortunately I can only share blast output

**Comment by ljyanesm** [comment] 2021-11-02 14:55
It is a shame you cannot share the rest of the data, please do share the blast output as it might help in resolving this issue, thank you

**Comment by ljyanesm** [comment] 2021-11-02 16:59
Dear @JulienPPichon,

Could you rerun serialise using the '--force' option? This clears the database in case any previous partial results are causing the issue.

I've checked the data and can confirm that there are no duplicated blast results in the input, which is what would be causing the error.

**Comment by JulienPPichon** [comment] 2021-11-02 17:35
Dear @ljyanesm 

I got the same error with the --force option.

I'm currently trying different combination of filtering of the blast output depending of the column. Surprisingly, serialise is working when for exemple I filter for an unique hit having a specific id_query, id_target and qstart, or having a specific id_query, id_target and alignment length. However it doesn't work for similar combination such as id_query, id_target and qend. It looks consistent with the hypothesis that a hit or several made serialise crash.

**Comment by ljyanesm** [comment] 2021-11-03 13:48
Dear @JulienPPichon,

Whilst I investigate further how this error is surfacing, could you also try filtering the blast output with a more stringent evalue and re-running serialise?

Alternatively although it would require re-running the blast alignments, you could use the `xml` format instead of `tsv`.

Many thanks for your patience,
Luis

**Comment by ljyanesm** [comment] 2021-11-03 18:14
Dear @JulienPPichon

Given you cannot provide the full dataset, I was wondering if you could you provide for the queries (the output of mikado prepare) and targets a file of the sequence name alongside the sequence length?

Many thanks,
Luis.

**Comment by JulienPPichon** [comment] 2021-11-04 10:46
Dear @ljyanesm 

Thank you very much for your help, I solved the issue putting a blast evalue < 10^-7. Unfortunately I cannot share those data... I still wondering what happened, filtering rnaseq reads also worked, so probably the issue come from the upstream pipeline.

Best,

**Comment by ljyanesm** [comment] 2021-11-04 12:17
Dear @JulienPPichon,

Sorry if I was misinterpreted, but I was wondering if you could share *only the lengths* not the actual sequences as that would be enough information to check exactly what was the issue. If this is still not possible please close the ticket, otherwise I'd want to leave it open whilst investigating.

Many thanks,
Luis

**Comment by JulienPPichon** [comment] 2021-11-04 13:32
Dear @ljyanesm,

Of course sorry, I misunderstood your request. Is this file okay ?
[seq_length.zip](https://github.com/EI-CoreBioinformatics/mikado/files/7475092/seq_length.zip)

Best,

**Comment by ljyanesm** [comment] 2021-11-04 14:15
And the same for the targets, thank you!

**Comment by JulienPPichon** [comment] 2021-11-04 16:25
[seq_length_target.zip](https://github.com/EI-CoreBioinformatics/mikado/files/7476464/seq_length_target.zip)

This is protein length

**Comment by ljyanesm** [comment] 2021-11-09 15:41
Dear @JulienPPichon,

We would be very grateful if you could try the current master branch of mikado with your data to confirm the issue is now also fixed in the codebase.

The issue was identified as an insufficiently strict uniqueness check for the hits, there were 4 non-unique pairs of hits after processing the input `tsv` file. These were identified as low quality, and according to the fields in the previous uniqueness check they were non-unique causing the issue you experienced. 

The PR in this issue adds another field (evalue), which we expect will resolve the issue.

**Comment by JulienPPichon** [comment] 2021-11-11 08:58
Dear @ljyanesm 

I serialised with my data without putting an e-value threshold for blast and everything worked great, looks like the issue is fixed !

Thank you very much for your help and good luck to continue to develop mikado and other amazing tools. 

Best,

**Closed** 2021-11-12 11:41 UTC
